from distutils.core import setup

setup(
    name='VOSpace',
    version='0.1',
    packages=['', 'env.lib.python3.5.distutils', 'env.lib.python3.5.encodings', 'env.lib.python3.5.importlib',
              'env.lib.python3.5.collections', 'env.lib.python3.5.site-packages.py',
              'env.lib.python3.5.site-packages.py._io', 'env.lib.python3.5.site-packages.py._log',
              'env.lib.python3.5.site-packages.py._code', 'env.lib.python3.5.site-packages.py._path',
              'env.lib.python3.5.site-packages.py._process', 'env.lib.python3.5.site-packages.pip',
              'env.lib.python3.5.site-packages.pip.req', 'env.lib.python3.5.site-packages.pip.vcs',
              'env.lib.python3.5.site-packages.pip.utils', 'env.lib.python3.5.site-packages.pip.compat',
              'env.lib.python3.5.site-packages.pip.models', 'env.lib.python3.5.site-packages.pip._vendor',
              'env.lib.python3.5.site-packages.pip._vendor.distlib',
              'env.lib.python3.5.site-packages.pip._vendor.distlib._backport',
              'env.lib.python3.5.site-packages.pip._vendor.colorama',
              'env.lib.python3.5.site-packages.pip._vendor.html5lib',
              'env.lib.python3.5.site-packages.pip._vendor.html5lib._trie',
              'env.lib.python3.5.site-packages.pip._vendor.html5lib.filters',
              'env.lib.python3.5.site-packages.pip._vendor.html5lib.treewalkers',
              'env.lib.python3.5.site-packages.pip._vendor.html5lib.treeadapters',
              'env.lib.python3.5.site-packages.pip._vendor.html5lib.treebuilders',
              'env.lib.python3.5.site-packages.pip._vendor.lockfile',
              'env.lib.python3.5.site-packages.pip._vendor.progress',
              'env.lib.python3.5.site-packages.pip._vendor.requests',
              'env.lib.python3.5.site-packages.pip._vendor.requests.packages',
              'env.lib.python3.5.site-packages.pip._vendor.requests.packages.chardet',
              'env.lib.python3.5.site-packages.pip._vendor.requests.packages.urllib3',
              'env.lib.python3.5.site-packages.pip._vendor.requests.packages.urllib3.util',
              'env.lib.python3.5.site-packages.pip._vendor.requests.packages.urllib3.contrib',
              'env.lib.python3.5.site-packages.pip._vendor.requests.packages.urllib3.packages',
              'env.lib.python3.5.site-packages.pip._vendor.requests.packages.urllib3.packages.ssl_match_hostname',
              'env.lib.python3.5.site-packages.pip._vendor.packaging',
              'env.lib.python3.5.site-packages.pip._vendor.cachecontrol',
              'env.lib.python3.5.site-packages.pip._vendor.cachecontrol.caches',
              'env.lib.python3.5.site-packages.pip._vendor.webencodings',
              'env.lib.python3.5.site-packages.pip._vendor.pkg_resources',
              'env.lib.python3.5.site-packages.pip.commands', 'env.lib.python3.5.site-packages.pip.operations',
              'env.lib.python3.5.site-packages.amqp', 'env.lib.python3.5.site-packages.bson',
              'env.lib.python3.5.site-packages.lxml', 'env.lib.python3.5.site-packages.lxml.html',
              'env.lib.python3.5.site-packages.lxml.includes', 'env.lib.python3.5.site-packages.lxml.isoschematron',
              'env.lib.python3.5.site-packages.pytz', 'env.lib.python3.5.site-packages.vine',
              'env.lib.python3.5.site-packages.click', 'env.lib.python3.5.site-packages.flask',
              'env.lib.python3.5.site-packages.flask.ext', 'env.lib.python3.5.site-packages.kombu',
              'env.lib.python3.5.site-packages.kombu.async', 'env.lib.python3.5.site-packages.kombu.async.aws',
              'env.lib.python3.5.site-packages.kombu.async.aws.sqs', 'env.lib.python3.5.site-packages.kombu.async.http',
              'env.lib.python3.5.site-packages.kombu.utils', 'env.lib.python3.5.site-packages.kombu.transport',
              'env.lib.python3.5.site-packages.kombu.transport.virtual',
              'env.lib.python3.5.site-packages.kombu.transport.sqlalchemy', 'env.lib.python3.5.site-packages.wheel',
              'env.lib.python3.5.site-packages.wheel.test',
              'env.lib.python3.5.site-packages.wheel.test.simple.dist.simpledist',
              'env.lib.python3.5.site-packages.wheel.test.complex-dist.complexdist',
              'env.lib.python3.5.site-packages.wheel.tool', 'env.lib.python3.5.site-packages.wheel.signatures',
              'env.lib.python3.5.site-packages.gridfs', 'env.lib.python3.5.site-packages.jinja2',
              'env.lib.python3.5.site-packages._pytest', 'env.lib.python3.5.site-packages._pytest._code',
              'env.lib.python3.5.site-packages._pytest.assertion',
              'env.lib.python3.5.site-packages._pytest.vendored_packages', 'env.lib.python3.5.site-packages.pymongo',
              'env.lib.python3.5.site-packages.tzlocal', 'env.lib.python3.5.site-packages.billiard',
              'env.lib.python3.5.site-packages.billiard.dummy', 'env.lib.python3.5.site-packages.dateutil',
              'env.lib.python3.5.site-packages.dateutil.tz', 'env.lib.python3.5.site-packages.dateutil.zoneinfo',
              'env.lib.python3.5.site-packages.werkzeug', 'env.lib.python3.5.site-packages.werkzeug.debug',
              'env.lib.python3.5.site-packages.werkzeug.contrib', 'env.lib.python3.5.site-packages.aniso8601',
              'env.lib.python3.5.site-packages.jsonschema', 'env.lib.python3.5.site-packages.jsonschema.tests',
              'env.lib.python3.5.site-packages.markupsafe', 'env.lib.python3.5.site-packages.setuptools',
              'env.lib.python3.5.site-packages.setuptools.extern', 'env.lib.python3.5.site-packages.setuptools.command',
              'env.lib.python3.5.site-packages.apscheduler', 'env.lib.python3.5.site-packages.apscheduler.triggers',
              'env.lib.python3.5.site-packages.pkg_resources', 'env.lib.python3.5.site-packages.pkg_resources.extern',
              'env.lib.python3.5.site-packages.pkg_resources._vendor',
              'env.lib.python3.5.site-packages.pkg_resources._vendor.packaging',
              'env.lib.python3.5.site-packages.flask_restplus'],
    url='http://cdsweb.u-strasbg.fr/',
    license='GNU GENERAL PUBLIC LICENSE',
    author='Bouchair Madjid',
    author_email='madjid.bouchair@gmail.com',
    description='Prototype de service VOSpace'
)
